device: cuda
output_dir: ./output
img_size: 64
num_img_to_sample: 16
random_seed: null

ckpt_path: path-to-ckpt
use_ema: true

width: 1
num_classes: 2
time_dim: 256
noise_steps: 1000
beta_start: 1e-4
beta_end: 2e-2
# cfg_scale: 3.0

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: ${output_dir}