task_name: DDPM_Uncond_Celeba_64

data_dir: /Users/petrushkovm/Downloads/celeba_hq_256
img_size: 64
batch_size: 4
num_workers: 0

lr: 3e-4
ddp: false
log_every: 1000
num_img_to_sample: 16
epochs: 100
resume_from: null

width: 2
num_classes: null
time_dim: 256
noise_steps: 1000
beta_start: 1e-4
beta_end: 2e-2
device: mps

beta_ema: 0.995
step_ema: 0
start_step_ema: 20000

# Paths configuration
log_dir: ./logs
output_dir: ${hydra:runtime.output_dir} # this dir is formed below

hydra:
  # Output directory for logs, checkpoints, etc.
  run:
    dir: ${log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
